# Generated by Django 2.1.2 on 2018-11-02 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0003_post_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('email', models.EmailField(max_length=255, verbose_name='邮箱地址')),
                ('text', models.TextField(verbose_name='评论正文')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('post', models.ForeignKey(on_delete=True, to='blog.Post', verbose_name='关联文章')),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
    ]
