# Generated by Django 2.1.2 on 2018-11-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181105_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='images/text02.jpg', upload_to='images/post_img/%Y/%m', verbose_name='文章配图'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='images/default.jpg', upload_to='images/user_photo/%Y/%m', verbose_name='用户头像'),
        ),
        migrations.AddField(
            model_name='user',
            name='talk_to_myself',
            field=models.TextField(blank=True, null=True, verbose_name='自白'),
        ),
    ]
