# Generated by Django 2.1.2 on 2018-11-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181106_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='QR_code',
            field=models.ImageField(default='images/default.jpg', upload_to='images/user_photo/%Y/%m', verbose_name='微信二维码'),
        ),
        migrations.AddField(
            model_name='user',
            name='we_chat',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='微信号'),
        ),
    ]
